choco install adobereader -y
choco install firefox -y
choco install 7zip.install -y
choco install chocolateygui -y
choco install notepadplusplus.install -y
choco install skype -y
choco install teamviewer -y
choco install treesizefree -y
choco install windirstat -y
choco install autoruns -y
choco install autohotkey -y
choco install kvrt -y
choco install k-litecodecpackfull -y
choco install cpu-z -y
choco install avastfreeantivirus -y
choco install sumo -y
choco install kodi -y