	global Enum_ProgramMessage := {1000: "Unknown error (%s)."
			, 1001: "File does not exist`n%s."
			, 1002: "%s array is missing."
			, 1003: "Your operating system (%s) is no longer supported by this AutoHotkey version %s."
			, 1004: "It is possible that the script is not fully operational on your AutoHotkey version %s.`nDo you want to continue anyway ?"
			, 1006: "%s array is empty."
			, 1007: "SysGet command failed for %s(%s)."
			, 1008: "%s coordinates (%s,%s) are outside the screen area."
			, 1009: "Gui handle parameter is missing."
			, 1010: "The control number (%s) is invalid."
			, 1011: "GetWindowInfo() failed due to LastError %s."
			, 1012: "The control list handle is empty."
			, 1013: "PostMessage, WM_QUIT to %s`nfailed due to error %s."
			, 1014: "Invalid ScrollBarSpeed parameter (%s). Must be between 1 and 4."
			, 1015: "SendMessage, WM_COPYDATA to %s`nfailed due to error %s - LastError %s."
			, 1016: "ScrollWindowEx() failed due to LastError %s."
			, 1017: "%s`ncannot be launched due to LastError %s."
			, 1018: "WinWait timed out failed for`n%s."
			, 1019: "GetScrollInfo(%s) failed due to LastError %s."
			, 1020: "SendMessage, WM_CLOSE to %s`nfailed due to error %s."}