choco install firefox -y
choco install 7zip.install -y
choco install chocolateygui -y
choco install treesizefree -y
choco install windirstat -y
choco install autohotkey -y
choco install cpu-z -y
choco install sumo -y
choco install kodi -y